version: '3.1'

services:

  unit:
    image: golang:1.9
    volumes:
      - .:/usr/src/myapp
      - /tmp/go:/go
    working_dir: /usr/src/myapp
    command: bash -c "pwd && go get -d -v -t && go test --cover -v ./... && go build -v -o go-demo"
